[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd backend && npm install --include=dev",
  "cd frontend && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/",
  "cd backend && npx prisma generate && npm run build"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"