[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm install --include=dev",
  "cd frontend && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/",
  "cd backend && node node_modules/prisma/build/index.js generate && npm run build"
]

[start]
cmd = "cd backend && node node_modules/prisma/build/index.js migrate deploy && npm start"