[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/",
  "cd backend && npx prisma generate && npm run build"
]

[start]
cmd = "cd backend && npm run start"